"""add otp table

Revision ID: 9b2e385974f5
Revises: 648967a40a8a
Create Date: 2025-12-09 23:48:22.857150

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b2e385974f5"
down_revision: Union[str, Sequence[str], None] = "648967a40a8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otps",
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "uuid",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "mobile_number", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False
        ),
        sa.Column("otp", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_otps_mobile_number"), "otps", ["mobile_number"], unique=False
    )
    op.create_index(op.f("ix_otps_uuid"), "otps", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_otps_uuid"), table_name="otps")
    op.drop_index(op.f("ix_otps_mobile_number"), table_name="otps")
    op.drop_table("otps")
    # ### end Alembic commands ###
